[package]
name = "sqlite-zstd"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

build_extension = []

[lib]
crate-type = ["cdylib"]

[dependencies]
zstd = "0.5.3"
anyhow = "1.0.35"
rand = "0.7.3"
serde_json = "1.0.60"
serde = { version = "1.0.118", features = ["derive"] }

owning_ref = "0.4.1"

log = "0.4.11"
env_logger = "0.8.2"
lazy_static = "1.4.0"
lru_time_cache = "0.11.3"

[dependencies.rusqlite]
path = "../rusqlite"
version = "0.24.2"
features = ["functions", "blob", "loadable_extension", "bundled"]

[dev-dependencies]
chrono = "0.4.19"
names = "0.11.0"

[dev-dependencies.rusqlite]
path = "../rusqlite"
# git = "https://github.com/gwenn/rusqlite"
# branch = "pr/loadable-extensions"
features = ["functions", "blob", "bundled"]

[profile.release]
lto = true
