[package]
name = "sqlite-zstd"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
zstd = "0.5.1"
anyhow = "1.0.26"
rand = "0.7.3"
serde_json = "1.0.48"
serde = "1.0.104"
chrono = "0.4.10"
owning_ref = "0.4.1"

[dependencies.rusqlite]
# git = "https://github.com/Genomicsplc/rusqlite", branch="pr/loadable-extensions"
path = "../rusqlite"
features=["functions", "blob", "loadable_extension"]

[profile.release]
lto = true
