[package]
name = "sqlite-zstd"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"
description = "Extension for sqlite that provides transparent dictionary-based row-level compression for sqlite"
repository = "github.com/phiresky/sqlite-zstd"
license = "LGPL-2.0-or-later"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

build_extension = ["rusqlite-le/loadable_extension"]

# debug_zstd = ["zstd/debug"]

[lib]
crate-type = ["cdylib"]

[dependencies]
zstd = {version = "0.6.0", git="https://github.com/phiresky/zstd-rs", branch="master", features=["bindgen"] }
#zstd = {version = "0.5.3", path="../zstd-rs"}
#zstd = {version = "=0.5.4"}
anyhow = "1.0.36"
rand = "0.8.0"
serde_json = "1.0.60"
serde = { version = "1.0.118", features = ["derive"] }

owning_ref = "0.4.1"

log = "0.4.11"
env_logger = "0.8.2"
lazy_static = "1.4.0"
lru_time_cache = "0.11.3"

[dependencies.rusqlite]
git = "https://github.com/phiresky/rusqlite"
package = "rusqlite-le"
branch = "loadable-extensions"
version = "0.24.2"
features = ["functions", "blob", "bundled", "array"]

[dev-dependencies]
chrono = "0.4.19"
names = "0.11.0"
pretty_assertions = "0.6.1"


[profile.release]
lto = true
