[package]
name = "sqlite-zstd"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
zstd = "0.5.2"
anyhow = "1.0.31"
rand = "0.7.3"
serde_json = "1.0.53"
serde = { version = "1.0.111", features = ["derive"] }
chrono = "0.4.11"
owning_ref = "0.4.1"
names = "0.11.0"

[dependencies.rusqlite]
path = "../rusqlite"
features = ["functions", "blob", "loadable_extension", "bundled"]

[dev-dependencies.rusqlite]
path = "../rusqlite"
# git = "https://github.com/gwenn/rusqlite"
# branch = "pr/loadable-extensions"
features = ["functions", "blob", "bundled"]

[profile.release]
lto = true
